version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - C:/Users/kebri/Desktop/workspace/demo/sampleGateway/new:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin